### ISSUE TITLE
No food spawns

### ISSUE THREAD

**Issue by EGUltraTM** [esx-community/esx_foodtruck#3]
It will trigger the esx_foodtruck:placeFood

but this event doesnt exist. 

Since this it also dont spawns some food to be able to use it

**Comment by EGUltraTM** [comment]
This happens when dont wear Working clothes. Need to disable being able to press without working clothes

**Comment by TemptressTeelia** [comment]
If you are adding food, you will need to tie it to a prop. And if that prop is new, then you need to put it in the script in about three places. So make sure you read the script.

**Comment by EGUltraTM** [comment]
adding food is no problem. 
It looks like a bug (cause of a missing If ) that when youre not wearing your working clothes the food cooking doesnt work cause it doesnt spawn on the grill and then also not as finished product.

**Comment by TemptressTeelia** [comment]
I always put on the uniform. Maybe it acts as a clock in. Which is very similar to other jobs. Without clocking in things don’t work.

**Comment by EGUltraTM** [comment]
yep. will insert something that you cant cook when you have no workwear with a message. Then its fine :D

**Comment by TemptressTeelia** [comment]
Also this is a wip so if you get more things fixed please PR.

**Comment by EGUltraTM** [comment]
yeah will make one when im finished. Also added the BBQ animation which fits to that grill so you really make an barbecue now and then stop the animation when the food is finished and so.

**Comment by EGUltraTM** [comment]
> You have to edit the 'Enter / Exit entity zone events'
> It does not use that to place the food, it uses esx.game.spawnobject to place the food. The grill works as intended if you comment out the check for isEating.

Hi buddy.

Can you maybe help what exactly you mean to comment out the isEating. 
This is the last bug i have and im not able to solve the food not spawning 🗡 
always need to get the workwear 2 times to get it work correctly.

**Comment by TemptressTeelia** [comment]
So i will be sharing a PR for a semi complete food truck. I have added more food. I have added the market. I have added the society fridge. And I have made the job society in the database. 
The only things left for me is the uniform. 
Clock in or in service to access the grill. 
And the animations for the cooking.

**Comment by EGUltraTM** [comment]
Nice. I will PR then the other stuff when yours is there. 
Then i inculded the animations and stuff and will also make an PR then. Only need to copy paste it from my side. I will also insert the Fridge to on service. Thanks for that :)
